### PR TITLE
consumer.py: allow multiple topics to be passed into subscribe()

### PR DESCRIPTION
**Pull request by myNameIsPatrick**
This is required to be able to listen to multiple topics simultaneously, as multiple calls to `Consumer.assign()` and `Consumer.subscribe()` (the confluent client versions) replace the previous assignment/subscription.

As `subscribe()` can take in a single topic or multiple topics now, this change is backwards compatible.

### CODE REVIEW

**Comment by cnweaver** [comment]
This all makes sense to me. Would it make sense to add a test for this? I have, unfortunately, never gotten the tests for this project to run successfully myself, though, so I'm a bit ambivalent about doing so.

**Comment by myNameIsPatrick** [comment]
> This all makes sense to me. Would it make sense to add a test for this? I have, unfortunately, never gotten the tests for this project to run successfully myself, though, so I'm a bit ambivalent about doing so.

I'm in the same boat as you unfortunately, so let me know what you're more comfortable with and I'll proceed accordingly.

**Comment by cnweaver** [comment]
If you've tested locally and this patch works (and it looks simple enough that it certainly should), then I would personally rather not waste a lot of time struggling with the test infrastructure. It's probably a longer term issue to find some way to fix the tests so that developers and users can actually work with them.

**Comment by myNameIsPatrick** [comment]
Yeah, that's right. I've tested locally and confirmed this works.

> then I would personally rather not waste a lot of time struggling with the test infrastructure. It's probably a longer term issue to find some way to fix the tests so that developers and users can actually work with them.

That sounds good to me as well.

**Pull request merged**
