### PR TITLE
Modify error callback to warn about TIMED_OUT error

### PR DESCRIPTION
**Pull request by deepchatterjeeligo**
Possible fix for issues like https://git.ligo.org/emfollow/gwcelery/-/issues/441

### CODE REVIEW

**Comment by cnweaver** [comment]
These error messages originate in librdkafka when it decides that the connection to the broker is not behaving well, and must be reconnected. This point in the code is one of the main steps in that happening: https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_broker.c#L918 .
As a result of this deeper understanding, I don't think we just want to hide these messages (even if we can), as they do reflect overhead, if nothing else, when the connection is torn down and recreated. The better solution may be to advise tuning `batch_timeout` to a value which is not so small as to trigger frequent failures. 
It should be noted from the code linked above that one can in theory also change the `socket.max.fails` setting, but that also doesn't seem very advisable, as it might lead to ignoring more serious connection problems; the maintainers strongly advise against changing `socket.max.fails`.

**Comment by deepchatterjeeligo** [comment]
Hi @cnweaver is there a recommendation about what is a good value to use? If you could also give some high level summary of the batch_timeout feature to someone (like me) who is not familiar with librdkafka. I have seen that setting batch_timeout to, say 1s, does not mean messages come in only after 1s.

**Comment by cnweaver** [comment]
Okay, so first, what the batch timeout is: When the client polls for new data, this is supposed to be more-or-less the length of time that the broker has to respond. Making the value larger helps efficiency, as the broker can wait longer to collect messages together into a larger batch, so fewer packets need to be sent. Obviously, though, such waiting increases the latency for getting new messages back to the client if messages become available infrequently. Making the value smaller lowers latency, since when the broker has a message to send, it will spend less time waiting for more to add to the batch before just sending it, but this also incurs the disadvantage that if no messages become available before the timeout expires, the broker must still send a response, even if it is empty, and if the client then immediately makes a new request, many more packets are exchanged. Aside from the timeout, there are also the limits on the batch size both in terms of messages and in terms of total data size, and if these are reached a response can be sent before the timeout expires. 

It's hard to pick a single, best value for this, when seeking low latency. The issue is that some of the latency derives from the network between the client and the broker (and there is also presumably some minimum time the broker needs to respond at all), and if the timeout is set lower than this the client will conclude that there is a communication problem because it keeps seeing the broker miss the requirement. In practical terms, I have not tended to have issues with timeouts of order 100ms, but at 10ms the timeout is virtually impossible to satisfy. However, one can certainly imagine that under bad network conditions 100ms might see problems as well. I think the saving grace here is that while one doesn't want to pick too low a value and be reconnecting constantly, having it happen sometimes is not a fatal error. 

As an aside, `librdkafka`'s code suggests that it can try to compute the actual average round trip time of requests and include it in the error mesages; unfortunately, the data may not be available, and in practice never seems to be. This is a shame, as it would be helpful. If such data can be obtained, one could imagine some sort of adaptive latency-minimizing mode which would monitor the round trip time and try to select a timeout which is as small as can actually be honored.

**Comment by deepchatterjeeligo** [comment]
FWIW, this led to a error type log messages, which we ignore in gwcelery's logging. Closing this PR.

**Pull request closed without merging**
