### PR TITLE
Work around librdkafka crash when using oauth_cb

### PR DESCRIPTION
**Pull request by lpsinger**
Work around edenhill/librdkafka#3263. Remove once confluent-kafka 1.9.0 has been released.

### CODE REVIEW

**Comment by cnweaver** [comment]
I haven't tested this with the actual `OAUTHBEARER` mechanism, but with plain SCRAM it seems safely innocuous.

**Comment by lpsinger** [comment]
Thank you!

**Comment by lpsinger** [comment]
Would you please do a release to pick up this fix?

**Comment by lpsinger** [comment]
Note that this is not entirely fixed in librdkafka 1.9.0, so this workaround will still be needed at the moment. See https://github.com/edenhill/librdkafka/issues/3871.

**Pull request merged**
